import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import worker from './worker.mjs';
import {createJob,uploadAsset,markReady,getJob,claimJob,completeJob,failJob,reportTemplate,validateReport,digest,now,quota,MAX_JOB_BYTES} from './store.mjs';
import {authenticate} from './oauth.mjs';

// Execute real SQLite SQL, not mocked query results; R2 is a byte-preserving fake.
function environment(){
 const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));
 const prepare=(sql,values=[])=>({bind(...v){return prepare(sql,v);},async first(){return db.prepare(sql).get(...values) || null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){return {meta:db.prepare(sql).run(...values)};}});
 const objects=new Map();let writes=0;
 return {DB:{prepare,async batch(statements){db.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}},
 BUCKET:{async put(key,value){writes++;objects.set(key,new Uint8Array(value));},async get(key){const b=objects.get(key);return b?{body:b.slice(),async text(){return new TextDecoder().decode(b);},async arrayBuffer(){return b.slice().buffer;}}:null;},async delete(key){objects.delete(key);}},
 PUBLIC_ORIGIN:'https://checkni.test',ADMIN_TOKEN:'a'.repeat(48),RENDER_TOKEN:'r'.repeat(48),SIGNING_KEY:'s'.repeat(48),MCP_READ_ONLY:'false',db,objects,get writes(){return writes;}};
}
const jobid=n=>'beta-'+n.toString(16).padStart(32,'0');
const payload=n=>({id:jobid(n),source_url:'https://auto.bazos.sk/inzerat/123/test.php',language:'sk'});
async function prepared(env,n=1){
 const id=jobid(n);await createJob(env,payload(n));
 const files=[];
 for(const [name,value]of [['raw_data.json','{"title":"Synthetic test","description":"Seller claim"}'],['listing_facts.json','{}'],['images/p001.jpg','synthetic-image-bytes'],['sheets/overview_001.jpg','synthetic-sheet-bytes']]){
  files.push(await uploadAsset(env,id,name,new TextEncoder().encode(value)));
 }
 const m={schema_version:1,title:'Synthetic test',photos:[{id:'p001',number:1,filename:'images/p001.jpg',status:'available',inspection:'not_inspected'}],sheets:[{id:'s001',filename:'sheets/overview_001.jpg',photo_ids:['p001']}],files,ai_calls:0,chargeable:false};
 await markReady(env,id,m);return {id,m};
}
function report(id){return {schema_version:1,job_id:id,verdict:'CAUTION',confidence:'LOW',summary:'The seller claims a service history but provides no supporting documents.',findings:[{title:'Service records absent',detail:'The supplied listing has no invoices.',next_step:'Ask for invoices before travelling.',evidence_type:'listing',confidence:'HIGH',photo_ids:[],source_ids:[]}],sources:[],questions:['Can the seller supply maintenance invoices?'],limitations:['No physical inspection was performed.'],photo_review:[{photo_id:'p001',level:'not_inspected'}]};}
function request(path,{method='GET',token,body,headers={}}={}){return new Request('https://checkni.test'+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{}),...headers},...(body!==undefined?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});}
async function access(env,scope='analysis:read analysis:write'){const t='t'.repeat(64);await env.DB.prepare('INSERT INTO oauth_tokens VALUES(?,?,?,?,?,?)').bind(await digest(t),'client','access',env.PUBLIC_ORIGIN+'/mcp',scope,now()+1000).run();return t;}
const rpc=(method,params={},token)=>request('/mcp',{method:'POST',token,body:{jsonrpc:'2.0',id:1,method,params}});

test('source uploads are durable and all photos start uninspected',async()=>{const e=environment(),{id}=await prepared(e);const j=await getJob(e,id);assert.equal(j.status,'WAITING_FOR_AI');assert.equal(JSON.parse(j.manifest).photos[0].inspection,'not_inspected');assert.equal(e.objects.size,4);assert.equal(j.report,null);});
test('incomplete upload cannot enter the review queue',async()=>{const e=environment();await createJob(e,payload(1));const other=environment(),{m}=await prepared(other);await assert.rejects(markReady(e,jobid(1),m),/Upload incomplete/);assert.equal((await getJob(e,jobid(1))).status,'PREPARING');});
test('duplicate uploads, creation and ready calls are idempotent',async()=>{const e=environment();await createJob(e,payload(1));const bytes=new TextEncoder().encode('{}');await uploadAsset(e,jobid(1),'raw_data.json',bytes);await uploadAsset(e,jobid(1),'raw_data.json',bytes);assert.equal(e.writes,1);await createJob(e,payload(1));assert.equal(e.db.prepare('SELECT count(*) n FROM jobs').get().n,1);const f=environment(),{id,m}=await prepared(f);await markReady(f,id,m);assert.equal((await getJob(f,id)).status,'WAITING_FOR_AI');});
test('reject conflicting source files and path traversal',async()=>{const e=environment();await createJob(e,payload(1));await uploadAsset(e,jobid(1),'raw_data.json',new Uint8Array([1]));await assert.rejects(uploadAsset(e,jobid(1),'raw_data.json',new Uint8Array([2])),/conflict/);await assert.rejects(uploadAsset(e,jobid(1),'../secret',new Uint8Array([1])),/Invalid asset/);});
test('daily and retained capacity stop admission',async()=>{const e=environment();for(let i=1;i<=10;i++)await createJob(e,payload(i));await assert.rejects(createJob(e,payload(11)),/capacity/);e.db.prepare('UPDATE jobs SET created_at=0').run();for(let i=11;i<=50;i++){await createJob(e,payload(i));e.db.prepare('UPDATE jobs SET created_at=0').run();}await assert.rejects(createJob(e,payload(51)),/capacity/);});
test('byte reservation rejects a job over 40 MB before R2 upload',async()=>{const e=environment();await createJob(e,payload(1));e.db.prepare('INSERT INTO assets(job_id,name,bytes,sha256) VALUES(?,?,?,?)').run(jobid(1),'raw_data.json',MAX_JOB_BYTES,'x');await assert.rejects(uploadAsset(e,jobid(1),'listing_facts.json',new Uint8Array([1])),/40 MB/);assert.equal(e.writes,0);});
test('only one concurrent reviewer acquires a live lease',async()=>{const e=environment(),{id}=await prepared(e);const results=await Promise.allSettled([claimJob(e,id),claimJob(e,id)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);});
test('expired lease can be reclaimed and old lease cannot publish',async()=>{const e=environment(),{id}=await prepared(e);const a=await claimJob(e,id);e.db.prepare('UPDATE jobs SET lease_until=0 WHERE id=?').run(id);const b=await claimJob(e,id);assert.notEqual(a.lease_token,b.lease_token);await assert.rejects(completeJob(e,id,a.lease_token,report(id)),/lease/);});
test('report publication is idempotent but not overwritable',async()=>{const e=environment(),{id}=await prepared(e),lease=await claimJob(e,id),r=report(id);assert.equal((await completeJob(e,id,lease.lease_token,r)).status,'DONE');assert.equal((await completeJob(e,id,lease.lease_token,r)).status,'DONE');await assert.rejects(completeJob(e,id,lease.lease_token,{...r,summary:'Different content'}),/already completed/);await assert.rejects(failJob(e,id,'Failure',lease.lease_token),/current state/);});
test('default template and unknown report fields are rejected',async()=>{const e=environment(),{id,m}=await prepared(e),j=await getJob(e,id);assert.throws(()=>validateReport(reportTemplate(j),id,m),/template/);assert.throws(()=>validateReport({...report(id),hidden_score:100},id,m),/Unexpected/);});
test('every photograph needs an honest inspection status',async()=>{const e=environment(),{id,m}=await prepared(e);const r=report(id);r.photo_review=[];assert.throws(()=>validateReport(r,id,m),/Every gallery/);r.photo_review=[{photo_id:'p999',level:'overview'}];assert.throws(()=>validateReport(r,id,m),/Invalid inspection/);r.photo_review=[{photo_id:'p001',level:'detail'}];m.photos[0].status='unreadable';assert.throws(()=>validateReport(r,id,m),/unavailable/);});
test('photo and web findings must reference inspected photos and existing sources',async()=>{const e=environment(),{id,m}=await prepared(e);const r=report(id);r.findings[0].photo_ids=['p001'];assert.throws(()=>validateReport(r,id,m),/uninspected/);r.photo_review[0].level='overview';r.findings[0].evidence_type='photo';validateReport(r,id,m);r.findings[0].source_ids=['fake'];assert.throws(()=>validateReport(r,id,m),/unknown source/);});
test('readiness roundtrip verifies storage without retaining a probe',async()=>{const e=environment(),r=await worker.fetch(request('/v1/ready',{token:e.RENDER_TOKEN}),e);assert.equal(r.status,200);assert.equal(e.objects.size,0);assert.equal(e.writes,1);});
test('ingest credentials cannot claim or publish reports',async()=>{const e=environment(),{id}=await prepared(e);assert.equal((await worker.fetch(request(`/v1/jobs/${id}/claim`,{method:'POST',token:e.RENDER_TOKEN,body:{}}),e)).status,403);assert.equal((await worker.fetch(request('/v1/jobs',{token:e.RENDER_TOKEN}),e)).status,404);});
test('public report excludes snapshot, OAuth secrets and review leases',async()=>{const e=environment(),{id}=await prepared(e);await claimJob(e,id);const r=await worker.fetch(request('/public/jobs/'+id),e),j=await r.json();assert.equal(j.report,null);assert.ok(!('manifest' in j));assert.ok(!('lease_token' in j));assert.equal((await worker.fetch(request('/v1/jobs/'+id),e)).status,401);});
test('malicious Origins are rejected before writes',async()=>{const e=environment();const r=await worker.fetch(request('/v1/jobs',{method:'POST',token:e.RENDER_TOKEN,body:payload(1),headers:{Origin:'https://attacker.invalid'}}),e);assert.equal(r.status,403);assert.equal(e.db.prepare('SELECT count(*) n FROM jobs').get().n,0);});
test('MCP initialize, discovery and notification framing',async()=>{const e=environment();const init=await(await worker.fetch(rpc('initialize',{protocolVersion:'2025-06-18'}),e)).json();assert.equal(init.result.protocolVersion,'2025-06-18');const list=await(await worker.fetch(rpc('tools/list'),e)).json();assert.equal(list.result.tools.length,7);assert.equal((await worker.fetch(request('/mcp',{method:'POST',body:{jsonrpc:'2.0',method:'notifications/initialized'}}),e)).status,202);assert.equal((await worker.fetch(request('/mcp'),e)).status,405);});
test('MCP missing authentication returns a linking challenge without any data',async()=>{const e=environment();const r=await(await worker.fetch(rpc('tools/call',{name:'checkniauto_list_pending',arguments:{}}),e)).json();assert.equal(r.result.isError,true);assert.match(r.result._meta['mcp/www_authenticate'][0],/resource_metadata/);});
test('MCP images are image content, with original photo mapping',async()=>{const e=environment(),{id}=await prepared(e),token=await access(e);const r=await(await worker.fetch(rpc('tools/call',{name:'checkniauto_get_collage',arguments:{job_id:id,sheet_id:'s001'}},token),e)).json();assert.equal(r.result.content[1].type,'image');assert.equal(Buffer.from(r.result.content[1].data,'base64').toString(),'synthetic-sheet-bytes');assert.deepEqual(JSON.parse(r.result.content[0].text).photo_ids,['p001']);assert.equal((await getJob(e,id)).status,'WAITING_FOR_AI');});
test('read-only mode exposes no write tools and read tokens cannot claim',async()=>{const e=environment(),{id}=await prepared(e),token=await access(e,'analysis:read');const r=await(await worker.fetch(rpc('tools/call',{name:'checkniauto_claim_analysis',arguments:{job_id:id}},token),e)).json();assert.equal(r.result.isError,true);assert.match(r.result._meta['mcp/www_authenticate'][0],/analysis:write/);e.MCP_READ_ONLY='true';const list=await(await worker.fetch(rpc('tools/list'),e)).json();assert.equal(list.result.tools.length,4);assert.ok(list.result.tools.every(t=>t.annotations.readOnlyHint));});
test('request quotas fail closed at the configured bound',async()=>{const e=environment();await quota(e,'test:2026-01-01',1);await assert.rejects(quota(e,'test:2026-01-01',1),/limit/);});
test('maintenance only deletes expired authentication data and old counters',async()=>{const e=environment(),{id}=await prepared(e);e.db.prepare('INSERT INTO counters VALUES(?,1)').run('login:'+new Date().toISOString().slice(0,10));e.db.prepare('INSERT INTO counters VALUES(?,1)').run('requests:2000-01-01');await worker.scheduled({},e);assert.equal(e.db.prepare('SELECT count(*) n FROM counters').get().n,1);assert.equal((await getJob(e,id)).status,'WAITING_FOR_AI');assert.equal(e.objects.size,4);});

test('OAuth DCR rejects arbitrary external callbacks',async()=>{const e=environment();assert.equal((await worker.fetch(request('/oauth/register',{method:'POST',body:{redirect_uris:['https://attacker.invalid/callback']}}),e)).status,400);});
test('OAuth S256, CSRF, audience binding, one-use codes and rotating refresh',async()=>{
 const e=environment(),redirect='https://chatgpt.com/connector_platform_oauth_redirect';
 const registration=await(await worker.fetch(request('/oauth/register',{method:'POST',body:{redirect_uris:[redirect]}}),e)).json();
 const verifier='v'.repeat(64),challenge=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))).toString('base64url');
 const params=new URLSearchParams({client_id:registration.client_id,redirect_uri:redirect,response_type:'code',code_challenge_method:'S256',code_challenge:challenge,resource:e.PUBLIC_ORIGIN+'/mcp',scope:'analysis:read analysis:write offline_access',state:'user-state'});
 const page=await worker.fetch(request('/oauth/authorize?'+params),e);assert.equal(page.status,200);
 const cookie=page.headers.get('Set-Cookie').split(';')[0],signed=(await page.text()).match(/name="signed" value="([^"]+)"/)[1];
 const authorize=new URLSearchParams({signed,secret:e.ADMIN_TOKEN});
 const form=(path,body,extra={})=>request(path,{method:'POST',body:body.toString(),headers:{'Content-Type':'application/x-www-form-urlencoded',...extra}});
 assert.equal((await worker.fetch(form('/oauth/authorize',authorize,{Origin:e.PUBLIC_ORIGIN}),e)).status,403);
 const grant=await worker.fetch(form('/oauth/authorize',authorize,{Origin:e.PUBLIC_ORIGIN,Cookie:cookie}),e);assert.equal(grant.status,303);
 const target=new URL(grant.headers.get('Location'));assert.equal(target.searchParams.get('state'),'user-state');assert.equal(target.searchParams.get('iss'),e.PUBLIC_ORIGIN);
 const exchange=new URLSearchParams({grant_type:'authorization_code',code:target.searchParams.get('code'),client_id:registration.client_id,redirect_uri:redirect,resource:e.PUBLIC_ORIGIN+'/mcp',code_verifier:verifier});
 const wrong=new URLSearchParams(exchange);wrong.set('code_verifier','x'.repeat(64));assert.equal((await worker.fetch(form('/oauth/token',wrong),e)).status,400);
 wrong.set('code_verifier',verifier);wrong.set('resource','https://other.invalid/mcp');assert.equal((await worker.fetch(form('/oauth/token',wrong),e)).status,400);
 const tokenResponse=await worker.fetch(form('/oauth/token',exchange),e);assert.equal(tokenResponse.status,200);const tokens=await tokenResponse.json();assert.ok(tokens.access_token);assert.equal((await worker.fetch(form('/oauth/token',exchange),e)).status,400);
 assert.ok(await authenticate(request('/mcp',{token:tokens.access_token}),e,'analysis:write'));
 const refresh=new URLSearchParams({grant_type:'refresh_token',client_id:registration.client_id,resource:e.PUBLIC_ORIGIN+'/mcp',refresh_token:tokens.refresh_token});
 const rotated=await(await worker.fetch(form('/oauth/token',refresh),e)).json();assert.ok(rotated.access_token);assert.notEqual(rotated.refresh_token,tokens.refresh_token);assert.equal((await worker.fetch(form('/oauth/token',refresh),e)).status,400);
});
